version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - restore_cache:
          key: poetrydeps-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: |
            poetry config settings.virtualenvs.in-project true
            poetry install -v
      - save_cache:
          key: poetrydeps-{{ checksum "poetry.lock" }}
          paths:
            - "./.venv"
      - run:
          name: Run lint
          command: |
            poetry run flake8 src tests --max-line-length=88 --max-complexity=10
      - run:
          name: Run mypy
          command: |
            poetry run mypy ./src/
      - run:
          name: Run tests
          command: |
            poetry run pytest -v ./tests --cov=src --cov-fail-under=90 --cov-report=html:/tmp/coverage
      - store_artifacts:
          path: /tmp/coverage
          destination: coverage
